version: '3'

services:
  postgres_db:
    container_name: postgres_fixsell_db
    image: postgres:15.5 # updated version
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
