export const EnvConfiguration = () => ({
  environment: process.env.NODE_ENV || 'dev',
  mongo_uri: process.env.MONGO_URI,
  mongo_db_name: process.env.MONGO_DB_NAME,
  postgres_password: process.env.POSTGRES_PASSWORD,
  postgres_db_name: process.env.POSTGRES_DB_NAME,
  postgres_db_host: process.env.POSTGRES_DB_HOST,
  postgres_db_port: process.env.POSTGRES_DB_PORT,
  postgres_db_username: process.env.POSTGRES_DB_USERNAME,
  jwt_seed: process.env.JWT_SEED,
  aws_access_key_id: process.env.AWS_ACCESS_KEY_ID,
  aws_secret_access_key: process.env.AWS_SECRET_ACCESS_KEY,
  aws_region: process.env.AWS_REGION,
  aws_bucket_name: process.env.AWS_BUCKET_NAME,
  host_api: process.env.HOST_API,
  port: process.env.PORT,
});
